// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  procesosSidebar: [{ type: "autogenerated", dirName: "procesos" }],
  estandaresSidebar: [{ type: "autogenerated", dirName: "estandares" }],
  guiasSidebar: [{ type: "autogenerated", dirName: "guias" }],
  politicasSidebar: [{ type: "autogenerated", dirName: "politicas" }],
  plantillasSidebar: [{ type: "autogenerated", dirName: "plantillas" }],
  validacionesSidebar: [{ type: "autogenerated", dirName: "validaciones" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
